import { StyleSheet, Platform, Dimensions } from "react-native";
import { theme } from "../../../../theme/theme";

const { height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#050505" },
  glowTopLeft: { position: "absolute", top: -50, left: -50, width: 250, height: 250, borderRadius: 125, backgroundColor: "#FF6B00", opacity: 0.1, blurRadius: 90 },
  glowTopRight: { position: "absolute", top: 150, right: -100, width: 250, height: 250, borderRadius: 125, backgroundColor: "#00E676", opacity: 0.05, blurRadius: 100 },
  
  header: { paddingTop: Platform.OS === "ios" ? 55 : 40, paddingBottom: 15, paddingHorizontal: 16, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)", zIndex: 10 },
  headerLeft: { flexDirection: "row", alignItems: "center" },
  btnVoltar: { width: 38, height: 38, borderRadius: 19, backgroundColor: "rgba(255,255,255,0.08)", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", marginRight: 12 },
  headerSubtitle: { color: "#FF6B00", fontSize: 10, fontWeight: "900", textTransform: "uppercase", letterSpacing: 1 },
  headerTitle: { fontSize: 20, fontWeight: "900", color: "#FFF", letterSpacing: -0.5 },
  
  monthSelectorCompact: { flexDirection: "row", alignItems: "center", backgroundColor: "#121212", borderRadius: 14, borderWidth: 1, borderColor: "#222", padding: 2 },
  monthArrowSm: { paddingHorizontal: 8, paddingVertical: 6 },
  monthCenterSm: { paddingHorizontal: 4, paddingVertical: 6, alignItems: "center", justifyContent: "center", flexDirection: 'row' },
  monthTextSm: { color: "#FFF", fontSize: 12, fontWeight: "800", textTransform: "uppercase" },

  stickyFilterContainer: { borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)", paddingVertical: 14 },
  modalidadeWrapper: { flexDirection: "row", marginHorizontal: 20, backgroundColor: "rgba(255,255,255,0.05)", borderRadius: 12, padding: 4, marginBottom: 12 },
  modalidadeBtn: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: "center" },
  modalidadeBtnAtiva: { backgroundColor: "#333", shadowColor: "#000", shadowOffset: {width:0, height:2}, shadowOpacity: 0.2, shadowRadius: 4, elevation: 3 },
  modalidadeText: { color: "#888", fontSize: 13, fontWeight: "bold" },
  modalidadeTextAtiva: { color: "#FFF", fontWeight: "900" },
  
  statusFilterScroll: { paddingHorizontal: 20, gap: 10, alignItems: 'center' },
  statusChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: "#1A1A1A", borderWidth: 1, borderColor: "#333", height: 'auto', justifyContent: 'center' },
  statusText: { color: "#888", fontSize: 12, fontWeight: "700" },

  scrollContent: { paddingBottom: 120 },
  sectionPadding: { padding: 20, paddingTop: 10 },
  heroCard: { borderRadius: 24, padding: 24, backgroundColor: "#121212", borderWidth: 1, borderColor: "#222", marginBottom: 16, position: "relative", overflow: "hidden", shadowColor: "#000", shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.5, shadowRadius: 20, elevation: 10 },
  heroGradient: { position: "absolute", top: 0, left: 0, right: 0, height: 100 },
  heroHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  heroTitle: { color: "#AAA", fontSize: 14, fontWeight: "600", textTransform: "uppercase", letterSpacing: 0.5 },
  heroValue: { color: "#FFF", fontSize: 38, fontWeight: "900", letterSpacing: -1.5, marginBottom: 24 },
  stackedBarContainer: { height: 10, flexDirection: "row", borderRadius: 5, overflow: "hidden", marginBottom: 16 },
  barSegment: { height: "100%" },
  barLegends: { flexDirection: "row", justifyContent: "space-between" },
  legendItem: { flexDirection: "row", alignItems: "center" },
  legendDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  legendText: { color: "#888", fontSize: 12, fontWeight: "600" },

  listContainer: { padding: 20, paddingTop: 0, gap: 16 },
  studentCard: { backgroundColor: "#121212", borderRadius: 24, padding: 20, borderWidth: 1, borderColor: "#222" },
  cardMain: { flexDirection: "row", alignItems: "center" },
  avatarWrapper: { position: "relative" },
  avatar: { width: 54, height: 54, borderRadius: 27, backgroundColor: "#222", borderWidth: 2, borderColor: "#333" },
  avatarStatusDot: { position: "absolute", bottom: 0, right: 0, width: 14, height: 14, borderRadius: 7, borderWidth: 2, borderColor: "#121212" },
  cardInfo: { flex: 1, marginLeft: 14, justifyContent: "center" },
  studentName: { color: "#FFF", fontSize: 16, fontWeight: "bold", marginBottom: 2, letterSpacing: 0.2 },
  studentTenure: { color: "#666", fontSize: 12, fontWeight: "600", marginBottom: 8 },
  statusBadge: { flexDirection: "row", alignItems: "center", alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  statusBadgeText: { fontSize: 11, fontWeight: "900", letterSpacing: 0.3, textTransform: "uppercase" },
  cardFinancial: { alignItems: "flex-end", justifyContent: "center" },
  studentValue: { color: "#FFF", fontSize: 18, fontWeight: "900", marginBottom: 4 },
  studentDate: { color: "#888", fontSize: 11, fontWeight: "600" },
  cardDivider: { height: 1, backgroundColor: "#222", marginVertical: 16 },
  cardActions: { flexDirection: "row", gap: 10 },
  btnAction: { flex: 1, height: 46, borderRadius: 14, flexDirection: "row", justifyContent: "center", alignItems: "center", borderWidth: 1 },
  btnActionWhatsApp: { backgroundColor: "#25D366", borderColor: "#25D366", shadowColor: "#25D366", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  btnActionWarning: { backgroundColor: "#FFD700", borderColor: "#FFD700", shadowColor: "#FFD700", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 4 },
  btnActionOutline: { backgroundColor: "rgba(0, 230, 118, 0.05)", borderColor: "rgba(0, 230, 118, 0.3)" },
  btnActionGhost: { backgroundColor: "#1A1A1A", borderColor: "#2A2A2A" },
  btnActionText: { fontWeight: "900", fontSize: 13, textTransform: "uppercase", letterSpacing: 0.5 },
  
  emptyStateContainer: { alignItems: "center", justifyContent: "center", paddingVertical: 50 },
  emptyStateIconBg: { width: 90, height: 90, borderRadius: 45, backgroundColor: "rgba(255, 255, 255, 0.05)", justifyContent: "center", alignItems: "center", marginBottom: 20, borderWidth: 1, borderColor: "#333" },
  emptyStateTitle: { color: "#FFF", fontSize: 24, fontWeight: "900", marginBottom: 10, letterSpacing: -0.5 },
  emptyStateDesc: { color: "#888", fontSize: 15, textAlign: "center", paddingHorizontal: 30, lineHeight: 24 },

  btnCentralPdf: { marginVertical: 10, borderRadius: 20, overflow: "hidden", borderWidth: 1, borderColor: "#333", backgroundColor: "#111" },
  btnPdfGradient: { flexDirection: "row", alignItems: "center", padding: 20, justifyContent: 'center' },

  modalDataOverlay: { flex: 1, justifyContent: "flex-end" },
  modalDataCard: { width: '100%', backgroundColor: "#121212", borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 24, paddingBottom: 40, borderWidth: 1, borderColor: "#333", shadowColor: "#000", shadowOffset: {width:0, height:10}, shadowOpacity: 0.5, shadowRadius: 20 },
  modalDataHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  modalDataAno: { color: "#FFF", fontSize: 22, fontWeight: "900" },
  modalDataArrow: { padding: 10, backgroundColor: "#1A1A1A", borderRadius: 12 },
  modalDataMesBtn: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: "#1A1A1A", borderRadius: 12, alignItems: "center", borderWidth: 1, borderColor: "#222", marginRight: 10 },
  modalDataMesBtnAtivo: { backgroundColor: "rgba(255, 107, 0, 0.2)", borderColor: "#FF6B00" },
  modalDataMesText: { color: "#888", fontSize: 14, fontWeight: "bold", textTransform: "uppercase" },
  modalDataMesTextAtivo: { color: "#FF6B00", fontWeight: "900" },
  modalDataCloseBtn: { alignItems: "center", paddingVertical: 14, backgroundColor: "#1A1A1A", borderRadius: 16, borderWidth: 1, borderColor: "#333", justifyContent: 'center' },
  modalDataCloseText: { color: "#888", fontWeight: "bold", fontSize: 16 },
  
  calWeekRow: { flexDirection: "row", justifyContent: "space-around", marginBottom: 10, marginTop: 10 },
  calWeekText: { color: "#888", fontSize: 12, fontWeight: "bold", width: 30, textAlign: "center" },
  calDaysGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: 'flex-start' },
  calDayBox: { width: `${100 / 7}%`, aspectRatio: 1, justifyContent: "center", alignItems: "center", marginVertical: 2 },
  calDayBoxSelected: { backgroundColor: "#FF6B00", borderRadius: 8 },
  calDayBoxBetween: { backgroundColor: "rgba(255, 107, 0, 0.2)" },
  calDayBoxToday: { borderWidth: 1, borderColor: theme.colors.primary, borderRadius: 8 },
  calDayText: { color: "#FFF", fontSize: 14, fontWeight: "600" },
  calDayTextSelected: { color: "#FFF", fontWeight: "900" },
  todayDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: theme.colors.primary, marginTop: 2 },

  fabOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, zIndex: 90 },
  fabMenu: { position: "absolute", bottom: Platform.OS === 'ios' ? 110 : 100, right: 20, zIndex: 100, alignItems: "flex-end", gap: 16 },
  fabMenuItem: { flexDirection: "row", alignItems: "center", gap: 12 },
  fabMenuText: { color: "#FFF", fontSize: 15, fontWeight: "bold", backgroundColor: "#1A1A1A", paddingHorizontal: 14, paddingVertical: 8, borderRadius: 12, overflow: "hidden", borderWidth: 1, borderColor: "#333" },
  fabMenuIcon: { width: 44, height: 44, borderRadius: 22, justifyContent: "center", alignItems: "center", shadowColor: "#000", shadowOffset: {width: 0, height: 4}, shadowOpacity: 0.3, shadowRadius: 5 },
  fab: { position: "absolute", bottom: Platform.OS === 'ios' ? 40 : 30, right: 20, shadowColor: "#FF6B00", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.4, shadowRadius: 10, elevation: 8, zIndex: 100 },
  fabGradient: { width: 60, height: 60, borderRadius: 30, justifyContent: "center", alignItems: "center" },

  modalContainer: { flex: 1, justifyContent: "flex-end" },
  modalCard: { backgroundColor: "#121212", borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 24, paddingBottom: Platform.OS === "ios" ? 40 : 24, borderWidth: 1, borderColor: "#222" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 },
  modalTitle: { color: "#FFF", fontSize: 20, fontWeight: "900", letterSpacing: -0.5 },
  modalCloseBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#1A1A1A", justifyContent: "center", alignItems: "center" },
  modalAlunoInfo: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1A", padding: 16, borderRadius: 16, marginBottom: 24, borderWidth: 1, borderColor: "#222" },
  modalAvatar: { width: 48, height: 48, borderRadius: 24, marginRight: 12 },
  modalAlunoNome: { color: "#FFF", fontSize: 16, fontWeight: "bold", marginBottom: 4 },
  modalAlunoDetalhe: { color: "#888", fontSize: 13, fontWeight: "600" },
  
  searchBarBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1A1A1A', paddingHorizontal: 16, height: 50, borderRadius: 14, borderWidth: 1, borderColor: '#333', marginBottom: 15 },
  listAlunosScroll: { maxHeight: 160, marginBottom: 20 },
  alunoListItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 14, backgroundColor: '#1A1A1A', marginBottom: 8, borderWidth: 1, borderColor: '#333' },
  alunoListItemAtivo: { borderColor: '#FF6B00', backgroundColor: 'rgba(255,107,0,0.1)' },
  alunoListAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#222', marginRight: 12 },
  alunoListNome: { color: '#FFF', fontSize: 14, fontWeight: 'bold', flex: 1 },

  inputLabel: { color: "#888", fontSize: 12, fontWeight: "bold", textTransform: "uppercase", marginBottom: 8, letterSpacing: 0.5 },
  inputBox: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1A", borderRadius: 16, paddingHorizontal: 16, height: 56, marginBottom: 20, borderWidth: 1, borderColor: "#333" },
  inputPrefix: { color: "#666", fontSize: 16, fontWeight: "bold", marginRight: 8 },
  input: { flex: 1, color: "#FFF", fontSize: 16, fontWeight: "600", height: "100%", outlineStyle: "none" },
  chipContainer: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 24 },
  chipBtn: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, backgroundColor: "#1A1A1A", borderWidth: 1, borderColor: "#333" },
  chipBtnAtiva: { backgroundColor: "rgba(255, 107, 0, 0.15)", borderColor: "#FF6B00" },
  chipText: { color: "#888", fontSize: 13, fontWeight: "700" },
  chipTextAtiva: { color: "#FF6B00", fontWeight: "900" },
  btnConfirmar: { flexDirection: "row", backgroundColor: "#00E676", height: 60, borderRadius: 16, justifyContent: "center", alignItems: "center", marginTop: 10, shadowColor: "#00E676", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 6 },
  btnConfirmarText: { color: "#000", fontSize: 16, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.5 },

  reciboPremiumContainer: { width: '100%', padding: 24, borderRadius: 24, borderWidth: 1, borderColor: '#333', position: 'relative', overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 15 }, shadowOpacity: 0.8, shadowRadius: 30, elevation: 15 },
  watermarkIcon: { position: 'absolute', top: '20%', right: -30, transform: [{ rotate: '-15deg' }] },
  reciboPremiumHeader: { alignItems: 'center', marginBottom: 20 },
  iconSuccessBg: { width: 56, height: 56, borderRadius: 28, backgroundColor: 'rgba(0, 230, 118, 0.1)', justifyContent: 'center', alignItems: 'center', marginBottom: 12, borderWidth: 1, borderColor: 'rgba(0, 230, 118, 0.3)' },
  reciboPremiumTitle: { color: '#FFF', fontSize: 18, fontWeight: '900', letterSpacing: 2, marginBottom: 4 },
  reciboPremiumSubtitle: { color: '#888', fontSize: 11, fontWeight: '600' },
  dashedLine: { width: '100%', height: 1, borderBottomWidth: 1, borderColor: '#333', borderStyle: 'dashed', marginVertical: 20 },
  reciboPremiumBody: { gap: 16 },
  reciboPremiumRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  reciboPremiumLabel: { color: '#888', fontSize: 12, fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: 0.5 },
  reciboPremiumValue: { color: '#FFF', fontSize: 14, fontWeight: 'bold', textAlign: 'right', flex: 1, paddingLeft: 20 },
  reciboPremiumFooter: { alignItems: 'center' },
  reciboPremiumTotalLabel: { color: '#00E676', fontSize: 12, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 4 },
  reciboPremiumTotalValue: { color: '#00E676', fontSize: 36, fontWeight: '900', letterSpacing: -1 },
  reciboPremiumBottomBrand: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 24, opacity: 0.5 },
  reciboPremiumBrandText: { color: '#FFF', fontSize: 10, fontWeight: 'bold', letterSpacing: 0.5 },
  btnSharePremium: { width: '100%', marginTop: 24, borderRadius: 16, shadowColor: "#0A84FF", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.4, shadowRadius: 10, elevation: 8 },
  btnShareGradient: { flexDirection: 'row', height: 56, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  btnShareText: { color: '#FFF', fontSize: 16, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.5 },
  btnVoltarRecibo: { marginTop: 16, padding: 12 },
  btnVoltarReciboText: { color: '#888', fontSize: 14, fontWeight: 'bold' }
});