import { Dimensions, Platform, StyleSheet } from "react-native";
import { theme } from "../../../../../theme/theme";
import {
  moderateScale,
  scale,
  verticalScale,
} from "../../../../../utils/responsive";

const { height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#050505" },
  glowTopLeft: {
    position: "absolute",
    top: verticalScale(-50),
    left: scale(-50),
    width: scale(250),
    height: scale(250),
    borderRadius: moderateScale(125),
    backgroundColor: "#FF6B00",
    opacity: 0.1,
    blurRadius: 90,
  },
  glowTopRight: {
    position: "absolute",
    top: verticalScale(150),
    right: scale(-100),
    width: scale(250),
    height: scale(250),
    borderRadius: moderateScale(125),
    backgroundColor: "#00E676",
    opacity: 0.05,
    blurRadius: 100,
  },

  header: {
    paddingTop: Platform.OS === "ios" ? verticalScale(55) : verticalScale(40),
    paddingBottom: verticalScale(12),
    paddingHorizontal: scale(16),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
    zIndex: 10,
  },
  headerLeft: { flexDirection: "row", alignItems: "center" },
  btnVoltar: {
    width: scale(36),
    height: scale(36),
    borderRadius: moderateScale(18),
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    marginRight: scale(10),
  },
  headerSubtitle: {
    color: "#FF6B00",
    fontSize: moderateScale(9),
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  headerTitle: {
    fontSize: moderateScale(18),
    fontWeight: "900",
    color: "#FFF",
    letterSpacing: -0.5,
  },

  monthSelectorCompact: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#121212",
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: "#222",
    padding: scale(2),
  },
  monthArrowSm: {
    paddingHorizontal: scale(6),
    paddingVertical: verticalScale(4),
  },
  monthCenterSm: {
    paddingHorizontal: scale(6),
    paddingVertical: verticalScale(4),
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  monthTextSm: {
    color: "#FFF",
    fontSize: moderateScale(11),
    fontWeight: "800",
    textTransform: "uppercase",
  },

  stickyFilterContainer: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
    paddingVertical: verticalScale(10),
  },
  modalidadeWrapper: {
    flexDirection: "row",
    marginHorizontal: scale(20),
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: moderateScale(10),
    padding: scale(3),
    marginBottom: verticalScale(10),
  },
  modalidadeBtn: {
    flex: 1,
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(8),
    alignItems: "center",
  },
  modalidadeBtnAtiva: {
    backgroundColor: "#333",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  modalidadeText: {
    color: "#888",
    fontSize: moderateScale(12),
    fontWeight: "bold",
  },
  modalidadeTextAtiva: { color: "#FFF", fontWeight: "900" },

  statusFilterScroll: {
    paddingHorizontal: scale(20),
    gap: scale(8),
    alignItems: "center",
  },
  statusChip: {
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(16),
    backgroundColor: "#1A1A1A",
    borderWidth: 1,
    borderColor: "#333",
    height: "auto",
    justifyContent: "center",
  },
  statusText: { color: "#888", fontSize: moderateScale(11), fontWeight: "700" },

  scrollContent: { paddingBottom: verticalScale(120) },
  sectionPadding: { padding: scale(16), paddingTop: verticalScale(10) },
    heroCard: {
    borderRadius: moderateScale(20),
    padding: scale(18),
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#222",
    marginBottom: verticalScale(12),
    position: "relative",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 8,
  },
  heroGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: verticalScale(80),
  },
  heroHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(8),
  },
  heroTitle: {
    color: "#AAA",
    fontSize: moderateScale(12),
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  heroValue: {
    color: "#FFF",
    fontSize: moderateScale(32),
    fontWeight: "900",
    letterSpacing: -1,
    marginBottom: verticalScale(20),
  },
  stackedBarContainer: {
    height: verticalScale(8),
    flexDirection: "row",
    borderRadius: moderateScale(4),
    overflow: "hidden",
    marginBottom: verticalScale(12),
  },
  barSegment: { height: "100%" },
  barLegends: { flexDirection: "row", justifyContent: "space-between" },
  legendItem: { flexDirection: "row", alignItems: "center" },
  legendDot: {
    width: scale(6),
    height: scale(6),
    borderRadius: moderateScale(3),
    marginRight: scale(6),
  },
  legendText: { color: "#888", fontSize: moderateScale(11), fontWeight: "600" },

  listContainer: { padding: scale(16), paddingTop: 0, gap: verticalScale(12) },
  studentCard: {
    backgroundColor: "#121212",
    borderRadius: moderateScale(20),
    padding: scale(16),
    borderWidth: 1,
    borderColor: "#222",
  },
  cardMain: { flexDirection: "row", alignItems: "center" },
  avatarWrapper: { position: "relative" },
  avatar: {
    width: scale(46),
    height: scale(46),
    borderRadius: moderateScale(23),
    backgroundColor: "#222",
    borderWidth: 2,
    borderColor: "#333",
  },
  avatarStatusDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: scale(12),
    height: scale(12),
    borderRadius: moderateScale(6),
    borderWidth: 2,
    borderColor: "#121212",
  },
  cardInfo: { flex: 1, marginLeft: scale(12), justifyContent: "center" },
  studentName: {
    color: "#FFF",
    fontSize: moderateScale(15),
    fontWeight: "bold",
    marginBottom: verticalScale(2),
    letterSpacing: 0.2,
  },
  studentTenure: {
    color: "#666",
    fontSize: moderateScale(11),
    fontWeight: "600",
    marginBottom: verticalScale(6),
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: scale(6),
    paddingVertical: verticalScale(3),
    borderRadius: moderateScale(6),
  },
  statusBadgeText: {
    fontSize: moderateScale(10),
    fontWeight: "900",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  cardFinancial: { alignItems: "flex-end", justifyContent: "center" },
  studentValue: {
    color: "#FFF",
    fontSize: moderateScale(16),
    fontWeight: "900",
    marginBottom: verticalScale(2),
  },
  studentDate: {
    color: "#888",
    fontSize: moderateScale(10),
    fontWeight: "600",
  },
  cardDivider: {
    height: 1,
    backgroundColor: "#222",
    marginVertical: verticalScale(14),
  },
  cardActions: { flexDirection: "row", gap: scale(8) },
  btnAction: {
    flex: 1,
    height: verticalScale(40),
    borderRadius: moderateScale(12),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  btnActionWhatsApp: {
    backgroundColor: "#25D366",
    borderColor: "#25D366",
    shadowColor: "#25D366",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  btnActionWarning: {
    backgroundColor: "#FFD700",
    borderColor: "#FFD700",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  btnActionOutline: {
    backgroundColor: "rgba(0, 230, 118, 0.05)",
    borderColor: "rgba(0, 230, 118, 0.3)",
  },
  btnActionGhost: { backgroundColor: "#1A1A1A", borderColor: "#2A2A2A" },
  btnActionText: {
    fontWeight: "900",
    fontSize: moderateScale(11),
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: verticalScale(40),
  },
  emptyStateIconBg: {
    width: scale(70),
    height: scale(70),
    borderRadius: moderateScale(35),
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: verticalScale(16),
    borderWidth: 1,
    borderColor: "#333",
  },
  emptyStateTitle: {
    color: "#FFF",
    fontSize: moderateScale(20),
    fontWeight: "900",
    marginBottom: verticalScale(8),
    letterSpacing: -0.5,
  },
  emptyStateDesc: {
    color: "#888",
    fontSize: moderateScale(14),
    textAlign: "center",
    paddingHorizontal: scale(30),
    lineHeight: moderateScale(22),
  },

  btnCentralPdf: {
    marginVertical: verticalScale(8),
    borderRadius: moderateScale(16),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#333",
    backgroundColor: "#111",
  },
  btnPdfGradient: {
    flexDirection: "row",
    alignItems: "center",
    padding: scale(16),
    justifyContent: "center",
  },

  modalDataOverlay: { flex: 1, justifyContent: "flex-end" },
  modalDataCard: {
    width: "100%",
    backgroundColor: "#121212",
    borderTopLeftRadius: moderateScale(28),
    borderTopRightRadius: moderateScale(28),
    padding: scale(20),
    paddingBottom: Platform.OS === "ios" ? verticalScale(35) : verticalScale(20),
    borderWidth: 1,
    borderColor: "#333",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
  },
  modalDataHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(16),
  },
  modalDataAno: {
    color: "#FFF",
    fontSize: moderateScale(20),
    fontWeight: "900",
  },
  modalDataArrow: {
    padding: scale(8),
    backgroundColor: "#1A1A1A",
    borderRadius: moderateScale(10),
  },
  modalDataMesBtn: {
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(8),
    backgroundColor: "#1A1A1A",
    borderRadius: moderateScale(10),
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#222",
    marginRight: scale(8),
  },
  modalDataMesBtnAtivo: {
    backgroundColor: "rgba(255, 107, 0, 0.2)",
    borderColor: "#FF6B00",
  },
  modalDataMesText: {
    color: "#888",
    fontSize: moderateScale(13),
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  modalDataMesTextAtivo: { color: "#FF6B00", fontWeight: "900" },
  modalDataCloseBtn: {
    alignItems: "center",
    paddingVertical: verticalScale(12),
    backgroundColor: "#1A1A1A",
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: "#333",
    justifyContent: "center",
  },
  modalDataCloseText: {
    color: "#888",
    fontWeight: "bold",
    fontSize: moderateScale(14),
  },

  calWeekRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: verticalScale(8),
    marginTop: verticalScale(8),
  },
  calWeekText: {
    color: "#888",
    fontSize: moderateScale(11),
    fontWeight: "bold",
    width: scale(30),
    textAlign: "center",
  },
  calDaysGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  calDayBox: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: verticalScale(2),
  },
  calDayBoxSelected: {
    backgroundColor: "#FF6B00",
    borderRadius: moderateScale(8),
  },
  calDayBoxBetween: { backgroundColor: "rgba(255, 107, 0, 0.2)" },
  calDayBoxToday: {
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderRadius: moderateScale(8),
  },
  calDayText: { color: "#FFF", fontSize: moderateScale(13), fontWeight: "600" },
  calDayTextSelected: { color: "#FFF", fontWeight: "900" },
  todayDot: {
    width: scale(4),
    height: scale(4),
    borderRadius: moderateScale(2),
    backgroundColor: theme.colors.primary,
    marginTop: verticalScale(2),
  },

  fabOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 90,
  },
  fabMenu: {
    position: "absolute",
    bottom: Platform.OS === "ios" ? verticalScale(100) : verticalScale(90),
    right: scale(20),
    zIndex: 100,
    alignItems: "flex-end",
    gap: verticalScale(12),
  },
  fabMenuItem: { flexDirection: "row", alignItems: "center", gap: scale(10) },
  fabMenuText: {
    color: "#FFF",
    fontSize: moderateScale(13),
    fontWeight: "bold",
    backgroundColor: "#1A1A1A",
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(10),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#333",
  },
  fabMenuIcon: {
    width: scale(40),
    height: scale(40),
    borderRadius: moderateScale(20),
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  fab: {
    position: "absolute",
    bottom: Platform.OS === "ios" ? verticalScale(30) : verticalScale(20),
    right: scale(20),
    shadowColor: "#FF6B00",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
    zIndex: 100,
  },
  fabGradient: {
    width: scale(56),
    height: scale(56),
    borderRadius: moderateScale(28),
    justifyContent: "center",
    alignItems: "center",
  },

  modalContainer: { flex: 1, justifyContent: "flex-end" },
  modalCard: {
    backgroundColor: "#121212",
    borderTopLeftRadius: moderateScale(28),
    borderTopRightRadius: moderateScale(28),
    padding: scale(20),
    paddingBottom: Platform.OS === "ios" ? verticalScale(35) : verticalScale(20),
    borderWidth: 1,
    borderColor: "#222",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(20),
  },
  modalTitle: {
    color: "#FFF",
    fontSize: moderateScale(18),
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  modalCloseBtn: {
    width: scale(36),
    height: scale(36),
    borderRadius: moderateScale(18),
    backgroundColor: "#1A1A1A",
    justifyContent: "center",
    alignItems: "center",
  },
  modalAlunoInfo: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    padding: scale(14),
    borderRadius: moderateScale(14),
    marginBottom: verticalScale(20),
    borderWidth: 1,
    borderColor: "#222",
  },
  modalAvatar: {
    width: scale(42),
    height: scale(42),
    borderRadius: moderateScale(21),
    marginRight: scale(12),
  },
  modalAlunoNome: {
    color: "#FFF",
    fontSize: moderateScale(15),
    fontWeight: "bold",
    marginBottom: verticalScale(2),
  },
  modalAlunoDetalhe: {
    color: "#888",
    fontSize: moderateScale(12),
    fontWeight: "600",
  },

  searchBarBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    paddingHorizontal: scale(14),
    height: verticalScale(46),
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: "#333",
    marginBottom: verticalScale(12),
  },
  listAlunosScroll: {
    maxHeight: verticalScale(150),
    marginBottom: verticalScale(16),
  },
  alunoListItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: scale(10),
    borderRadius: moderateScale(12),
    backgroundColor: "#1A1A1A",
    marginBottom: verticalScale(6),
    borderWidth: 1,
    borderColor: "#333",
  },
  alunoListItemAtivo: {
    borderColor: "#FF6B00",
    backgroundColor: "rgba(255,107,0,0.1)",
  },
  alunoListAvatar: {
    width: scale(36),
    height: scale(36),
    borderRadius: moderateScale(18),
    backgroundColor: "#222",
    marginRight: scale(10),
  },
  alunoListNome: {
    color: "#FFF",
    fontSize: moderateScale(13),
    fontWeight: "bold",
    flex: 1,
  },

  inputLabel: {
    color: "#888",
    fontSize: moderateScale(11),
    fontWeight: "bold",
    textTransform: "uppercase",
    marginBottom: verticalScale(6),
    letterSpacing: 0.5,
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    borderRadius: moderateScale(14),
    paddingHorizontal: scale(14),
    height: verticalScale(50),
    marginBottom: verticalScale(16),
    borderWidth: 1,
    borderColor: "#333",
  },
  inputPrefix: {
    color: "#666",
    fontSize: moderateScale(15),
    fontWeight: "bold",
    marginRight: scale(8),
  },
  input: {
    flex: 1,
    color: "#FFF",
    fontSize: moderateScale(15),
    fontWeight: "600",
    height: "100%",
    outlineStyle: "none",
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: scale(8),
    marginBottom: verticalScale(20),
  },
  chipBtn: {
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(8),
    borderRadius: moderateScale(10),
    backgroundColor: "#1A1A1A",
    borderWidth: 1,
    borderColor: "#333",
  },
  chipBtnAtiva: {
    backgroundColor: "rgba(255, 107, 0, 0.15)",
    borderColor: "#FF6B00",
  },
  chipText: { color: "#888", fontSize: moderateScale(12), fontWeight: "700" },
  chipTextAtiva: { color: "#FF6B00", fontWeight: "900" },
  btnConfirmar: {
    flexDirection: "row",
    backgroundColor: "#00E676",
    height: verticalScale(52),
    borderRadius: moderateScale(14),
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(8),
    shadowColor: "#00E676",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  btnConfirmarText: {
    color: "#000",
    fontSize: moderateScale(14),
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  reciboPremiumContainer: {
    width: "100%",
    padding: scale(20),
    borderRadius: moderateScale(20),
    borderWidth: 1,
    borderColor: "#333",
    position: "relative",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  watermarkIcon: {
    position: "absolute",
    top: "20%",
    right: -25,
    transform: [{ rotate: "-15deg" }],
  },
  reciboPremiumHeader: {
    alignItems: "center",
    marginBottom: verticalScale(16),
  },
  iconSuccessBg: {
    width: scale(48),
    height: scale(48),
    borderRadius: moderateScale(24),
    backgroundColor: "rgba(0, 230, 118, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: verticalScale(10),
    borderWidth: 1,
    borderColor: "rgba(0, 230, 118, 0.3)",
  },
  reciboPremiumTitle: {
    color: "#FFF",
    fontSize: moderateScale(16),
    fontWeight: "900",
    letterSpacing: 1.5,
    marginBottom: verticalScale(2),
  },
  reciboPremiumSubtitle: {
    color: "#888",
    fontSize: moderateScale(10),
    fontWeight: "600",
  },
  dashedLine: {
    width: "100%",
    height: 1,
    borderBottomWidth: 1,
    borderColor: "#333",
    borderStyle: "dashed",
    marginVertical: verticalScale(16),
  },
  reciboPremiumBody: { gap: verticalScale(12) },
  reciboPremiumRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reciboPremiumLabel: {
    color: "#888",
    fontSize: moderateScale(11),
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  reciboPremiumValue: {
    color: "#FFF",
    fontSize: moderateScale(13),
    fontWeight: "bold",
    textAlign: "right",
    flex: 1,
    paddingLeft: scale(16),
  },
  reciboPremiumFooter: { alignItems: "center" },
  reciboPremiumTotalLabel: {
    color: "#00E676",
    fontSize: moderateScale(11),
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: verticalScale(2),
  },
  reciboPremiumTotalValue: {
    color: "#00E676",
    fontSize: moderateScale(30),
    fontWeight: "900",
    letterSpacing: -1,
  },
  reciboPremiumBottomBrand: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(20),
    opacity: 0.5,
  },
  reciboPremiumBrandText: {
    color: "#FFF",
    fontSize: moderateScale(9),
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  btnSharePremium: {
    width: "100%",
    marginTop: verticalScale(20),
    borderRadius: moderateScale(14),
    shadowColor: "#0A84FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  btnShareGradient: {
    flexDirection: "row",
    height: verticalScale(50),
    borderRadius: moderateScale(14),
    justifyContent: "center",
    alignItems: "center",
  },
  btnShareText: {
    color: "#FFF",
    fontSize: moderateScale(14),
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  btnVoltarRecibo: { marginTop: verticalScale(12), padding: scale(10) },
  btnVoltarReciboText: {
    color: "#888",
    fontSize: moderateScale(13),
    fontWeight: "bold",
  },
});