import { Platform, StyleSheet } from "react-native";
import { theme } from "../../../../../theme/theme";
import {
    moderateScale,
    scale,
    verticalScale,
} from "../../../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  
  glowTopLeft: {
    position: "absolute",
    top: verticalScale(-50),
    left: scale(-50),
    width: scale(300),
    height: scale(300),
    borderRadius: moderateScale(150),
    backgroundColor: "#0A84FF",
    opacity: 0.15,
    blurRadius: 100,
  },
  glowBottomRight: {
    position: "absolute",
    bottom: verticalScale(-50),
    right: scale(-50),
    width: scale(300),
    height: scale(300),
    borderRadius: moderateScale(150),
    backgroundColor: "#FF6B00",
    opacity: 0.1,
    blurRadius: 100,
  },

  header: {
    paddingTop: Platform.OS === "ios" ? verticalScale(55) : verticalScale(35),
    paddingBottom: verticalScale(12),
    paddingHorizontal: scale(16),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
    zIndex: 10,
  },
  btnVoltar: {
    width: scale(38),
    height: scale(38),
    borderRadius: moderateScale(19),
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  headerSubtitle: {
    color: "#0A84FF",
    fontSize: moderateScale(10),
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  headerTitle: {
    fontSize: moderateScale(20),
    fontWeight: "900",
    color: "#FFF",
    letterSpacing: -0.5,
  },

  scrollContent: { padding: scale(16), paddingBottom: verticalScale(100) },
  
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(12),
    marginTop: verticalScale(12),
  },
  sectionTitle: {
    color: "#FFF",
    fontSize: moderateScale(16),
    fontFamily: theme.fonts.title,
    marginLeft: scale(8),
    letterSpacing: 0.5,
  },

  btnInfo: { padding: scale(4), marginLeft: scale(6), opacity: 0.8 },
  infoModalIconBox: {
    width: scale(56),
    height: scale(56),
    borderRadius: moderateScale(28),
    backgroundColor: "rgba(10, 132, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: verticalScale(16),
    borderWidth: 1,
    borderColor: "rgba(10, 132, 255, 0.3)",
  },
  infoModalText: {
    color: "#CCC",
    fontSize: moderateScale(14),
    lineHeight: moderateScale(22),
    marginBottom: verticalScale(20),
  },
  infoModalDicaBox: {
    backgroundColor: "rgba(255, 215, 0, 0.08)",
    padding: scale(14),
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: "rgba(255, 215, 0, 0.3)",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(10),
  },
  infoModalDicaText: {
    color: "#FFD700",
    fontSize: moderateScale(12),
    flex: 1,
    marginLeft: scale(10),
    fontWeight: "600",
    lineHeight: moderateScale(16),
  },

  scoreCard: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: moderateScale(20),
    padding: scale(16),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    marginBottom: verticalScale(20),
  },
  scoreMainRow: { flexDirection: "row", alignItems: "center" },
  scoreCircle: {
    width: scale(68),
    height: scale(68),
    borderRadius: moderateScale(34),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3.5,
    marginRight: scale(14),
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
  scoreNumber: {
    color: "#FFF",
    fontSize: moderateScale(24),
    fontWeight: "900",
  },
  scoreTextContainer: { flex: 1 },
  scoreLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(4),
  },
  scoreLabel: {
    color: "#AAA",
    fontSize: moderateScale(10),
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  scoreStatusTitle: {
    color: "#FFF",
    fontSize: moderateScale(16),
    fontWeight: "900",
    marginBottom: verticalScale(2),
  },
  scoreDesc: {
    color: "#888",
    fontSize: moderateScale(11),
    lineHeight: moderateScale(15),
  },

  scoreRaioXContainer: {
    marginTop: verticalScale(12),
    paddingTop: verticalScale(12),
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
  },
  scoreRaioXItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: verticalScale(6),
  },
  scoreRaioXText: {
    color: "#CCC",
    fontSize: moderateScale(11),
    flex: 1,
    marginLeft: scale(8),
    lineHeight: moderateScale(15),
  },

  mrrCard: {
    backgroundColor: "#121212",
    borderRadius: moderateScale(20),
    padding: scale(20),
    borderWidth: 1,
    borderColor: "#222",
    marginBottom: verticalScale(20),
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  mrrHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(12),
  },
  mrrLabelRow: { flexDirection: "row", alignItems: "center" },
  mrrLabel: {
    color: "#AAA",
    fontSize: moderateScale(11),
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  mrrValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginBottom: verticalScale(16),
  },
  mrrValue: {
    color: "#FFF",
    fontSize: moderateScale(36),
    fontWeight: "900",
    letterSpacing: -1.5,
  },
  badgeGrowth: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(4),
    borderRadius: moderateScale(10),
    marginLeft: scale(10),
    marginBottom: verticalScale(6),
    borderWidth: 1,
  },
  badgeGrowthText: { fontSize: moderateScale(12), fontWeight: "900" },
  mrrHistoryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
    paddingTop: verticalScale(12),
    marginBottom: verticalScale(12),
  },
  mrrHistoryItem: { flex: 1 },
  mrrHistoryLabel: {
    color: "#888",
    fontSize: moderateScale(10),
    fontWeight: "bold",
    textTransform: "uppercase",
    marginBottom: verticalScale(4),
  },
  mrrHistoryValue: {
    color: "#FFF",
    fontSize: moderateScale(14),
    fontWeight: "900",
  },

  metaProgressoContainer: {
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: scale(14),
    borderRadius: moderateScale(14),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  metaProgressoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: verticalScale(6),
  },
  metaProgressoLabel: {
    color: "#FFF",
    fontSize: moderateScale(11),
    fontWeight: "bold",
  },
  metaProgressoValue: {
    color: "#0A84FF",
    fontSize: moderateScale(11),
    fontWeight: "900",
  },
  metaBarBg: {
    height: verticalScale(6),
    backgroundColor: "#222",
    borderRadius: moderateScale(3),
    overflow: "hidden",
  },
  metaBarFill: {
    height: "100%",
    backgroundColor: "#0A84FF",
    borderRadius: moderateScale(3),
  },

  insightPredicaoBox: {
    flexDirection: "row",
    backgroundColor: "rgba(10, 132, 255, 0.1)",
    padding: scale(12),
    borderRadius: moderateScale(14),
    marginTop: verticalScale(12),
    borderWidth: 1,
    borderColor: "rgba(10, 132, 255, 0.2)",
    alignItems: "center",
  },
  insightPredicaoText: {
    flex: 1,
    color: "#0A84FF",
    fontSize: moderateScale(11),
    fontWeight: "bold",
    marginLeft: scale(8),
    lineHeight: moderateScale(16),
  },

  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: verticalScale(8),
  },
  kpiBox: {
    width: "48%",
    backgroundColor: "#121212",
    borderRadius: moderateScale(18),
    padding: scale(14),
    borderWidth: 1,
    borderColor: "#222",
    marginBottom: verticalScale(12),
  },
  kpiIconBg: {
    width: scale(32),
    height: scale(32),
    borderRadius: moderateScale(10),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: verticalScale(10),
  },
  kpiLabel: {
    color: "#888",
    fontSize: moderateScale(10),
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: verticalScale(4),
  },
  kpiValue: { color: "#FFF", fontSize: moderateScale(18), fontWeight: "900" },

  distContainer: {
    backgroundColor: "#121212",
    borderRadius: moderateScale(20),
    padding: scale(16),
    borderWidth: 1,
    borderColor: "#222",
    marginBottom: verticalScale(20),
  },
  stackedBar: {
    flexDirection: "row",
    height: verticalScale(14),
    borderRadius: moderateScale(7),
    overflow: "hidden",
    marginBottom: verticalScale(16),
    backgroundColor: "#222",
  },
  distLegendContainer: { flexDirection: "column", gap: verticalScale(10) },
  distLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  distLegendLeft: { flexDirection: "row", alignItems: "center" },
  distDot: {
    width: scale(8),
    height: scale(8),
    borderRadius: moderateScale(4),
    marginRight: scale(8),
  },
  distLabel: { color: "#AAA", fontSize: moderateScale(12), fontWeight: "bold" },
  distValue: { color: "#FFF", fontSize: moderateScale(13), fontWeight: "900" },

  funilContainer: {
    backgroundColor: "#121212",
    borderRadius: moderateScale(20),
    padding: scale(16),
    borderWidth: 1,
    borderColor: "#222",
    marginBottom: verticalScale(20),
  },
  funilEtapa: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(12),
  },
  funilBarBg: {
    flex: 1,
    height: verticalScale(30),
    backgroundColor: "#1A1A1A",
    borderRadius: moderateScale(10),
    overflow: "hidden",
    marginLeft: scale(12),
    justifyContent: "center",
  },
  funilBarFill: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    borderRadius: moderateScale(10),
  },
  funilEtapaLabel: {
    width: scale(80),
    color: "#AAA",
    fontSize: moderateScale(11),
    fontWeight: "bold",
  },
  funilEtapaValue: {
    color: "#FFF",
    fontSize: moderateScale(13),
    fontWeight: "900",
    position: "absolute",
    right: scale(12),
    zIndex: 2,
  },

  funilTempoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: verticalScale(12),
    paddingTop: verticalScale(12),
    borderTopWidth: 1,
    borderTopColor: "#222",
  },
  funilTempoBox: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: scale(10),
    borderRadius: moderateScale(10),
    alignItems: "center",
    marginHorizontal: scale(4),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  funilTempoLabel: {
    color: "#888",
    fontSize: moderateScale(9),
    fontWeight: "bold",
    textTransform: "uppercase",
    marginBottom: verticalScale(2),
    textAlign: "center",
  },
  funilTempoValue: {
    color: "#FFF",
    fontSize: moderateScale(15),
    fontWeight: "900",
  },

  selosGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: scale(10),
    marginBottom: verticalScale(16),
  },
  seloCard: {
    width: "31%",
    backgroundColor: "rgba(255,215,0,0.05)",
    borderRadius: moderateScale(14),
    padding: scale(12),
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.3)",
  },
  seloIconBox: {
    width: scale(36),
    height: scale(36),
    borderRadius: moderateScale(18),
    backgroundColor: "rgba(255,215,0,0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: verticalScale(6),
  },
  seloTitle: {
    color: "#FFD700",
    fontSize: moderateScale(10),
    fontWeight: "bold",
    textAlign: "center",
  },

  modalContainer: { flex: 1, justifyContent: "flex-end" },
  modalCard: {
    backgroundColor: "#121212",
    borderTopLeftRadius: moderateScale(28),
    borderTopRightRadius: moderateScale(28),
    padding: scale(20),
    paddingBottom:
      Platform.OS === "ios" ? verticalScale(35) : verticalScale(20),
    borderWidth: 1,
    borderColor: "#222",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(20),
  },
  modalTitle: {
    color: "#FFF",
    fontSize: moderateScale(18),
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  modalCloseBtn: {
    width: scale(36),
    height: scale(36),
    borderRadius: moderateScale(18),
    backgroundColor: "#1A1A1A",
    justifyContent: "center",
    alignItems: "center",
  },
  inputLabel: {
    color: "#888",
    fontSize: moderateScale(11),
    fontWeight: "bold",
    textTransform: "uppercase",
    marginBottom: verticalScale(6),
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    borderRadius: moderateScale(14),
    paddingHorizontal: scale(14),
    height: verticalScale(54),
    marginBottom: verticalScale(16),
    borderWidth: 1,
    borderColor: "#333",
  },
  inputPrefix: {
    color: "#666",
    fontSize: moderateScale(14),
    fontWeight: "bold",
    marginRight: scale(8),
  },
  input: {
    flex: 1,
    color: "#FFF",
    fontSize: moderateScale(15),
    fontWeight: "600",
    height: "100%",
    outlineStyle: "none",
  },
  btnConfirmar: {
    flexDirection: "row",
    backgroundColor: "#0A84FF",
    height: verticalScale(54),
    borderRadius: moderateScale(14),
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(8),
  },
  btnConfirmarText: {
    color: "#FFF",
    fontSize: moderateScale(15),
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  aiCardContainer: {
    backgroundColor: "rgba(160, 32, 240, 0.1)",
    borderRadius: moderateScale(20),
    padding: scale(16),
    borderWidth: 1,
    borderColor: "rgba(160, 32, 240, 0.4)",
    marginBottom: verticalScale(20),
    shadowColor: "#A020F0",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  aiHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: verticalScale(10),
  },
  aiTitle: {
    color: "#FFF",
    fontSize: moderateScale(15),
    fontWeight: "900",
    marginLeft: scale(8),
    letterSpacing: 0.5,
  },
  aiText: {
    color: "#E0E0E0",
    fontSize: moderateScale(12),
    lineHeight: moderateScale(18),
  },
});