import { StyleSheet, Platform } from "react-native";
import { theme } from "../../../../theme/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  glowTopLeft: { position: "absolute", top: -50, left: -50, width: 300, height: 300, borderRadius: 150, backgroundColor: "#0A84FF", opacity: 0.15, blurRadius: 100 },
  glowBottomRight: { position: "absolute", bottom: -50, right: -50, width: 300, height: 300, borderRadius: 150, backgroundColor: "#FF6B00", opacity: 0.1, blurRadius: 100 },
  header: { paddingTop: Platform.OS === "ios" ? 60 : 40, paddingBottom: 15, paddingHorizontal: 20, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)", zIndex: 10 },
  btnVoltar: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.08)", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  headerSubtitle: { color: "#0A84FF", fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 1.5 },
  headerTitle: { fontSize: 22, fontWeight: "900", color: "#FFF", letterSpacing: -0.5 },
  scrollContent: { padding: 20, paddingBottom: 100 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 15, marginTop: 15 },
  sectionTitle: { color: "#FFF", fontSize: 18, fontFamily: theme.fonts.title, marginLeft: 8, letterSpacing: 0.5 },

  btnInfo: { padding: 4, marginLeft: 6, opacity: 0.8 },
  infoModalIconBox: { width: 64, height: 64, borderRadius: 32, backgroundColor: "rgba(10, 132, 255, 0.1)", justifyContent: "center", alignItems: "center", marginBottom: 20, borderWidth: 1, borderColor: "rgba(10, 132, 255, 0.3)" },
  infoModalText: { color: "#CCC", fontSize: 15, lineHeight: 24, marginBottom: 24 },
  infoModalDicaBox: { backgroundColor: "rgba(255, 215, 0, 0.08)", padding: 16, borderRadius: 16, borderWidth: 1, borderColor: "rgba(255, 215, 0, 0.3)", flexDirection: "row", alignItems: "center", marginBottom: 10 },
  infoModalDicaText: { color: "#FFD700", fontSize: 13, flex: 1, marginLeft: 12, fontWeight: "600", lineHeight: 18 },

  scoreCard: { backgroundColor: "rgba(255,255,255,0.03)", borderRadius: 24, padding: 20, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", marginBottom: 25 },
  scoreMainRow: { flexDirection: 'row', alignItems: 'center' },
  scoreCircle: { width: 80, height: 80, borderRadius: 40, justifyContent: 'center', alignItems: 'center', borderWidth: 4, marginRight: 16, shadowOffset: {width: 0, height: 0}, shadowOpacity: 0.8, shadowRadius: 10 },
  scoreNumber: { color: "#FFF", fontSize: 28, fontWeight: "900" },
  scoreTextContainer: { flex: 1 },
  scoreLabelRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  scoreLabel: { color: "#AAA", fontSize: 12, fontWeight: "bold", textTransform: "uppercase", letterSpacing: 1 },
  scoreStatusTitle: { color: "#FFF", fontSize: 18, fontWeight: "900", marginBottom: 2 },
  scoreDesc: { color: "#888", fontSize: 12, lineHeight: 16 },
  
  scoreRaioXContainer: { marginTop: 15, paddingTop: 15, borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.05)" },
  scoreRaioXItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  scoreRaioXText: { color: "#CCC", fontSize: 12, flex: 1, marginLeft: 8, lineHeight: 16 },

  mrrCard: { backgroundColor: "#121212", borderRadius: 24, padding: 24, borderWidth: 1, borderColor: "#222", marginBottom: 25, overflow: 'hidden', shadowColor: "#000", shadowOffset: {width: 0, height: 10}, shadowOpacity: 0.5, shadowRadius: 15, elevation: 10 },
  mrrHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 15 },
  mrrLabelRow: { flexDirection: 'row', alignItems: 'center' },
  mrrLabel: { color: "#AAA", fontSize: 13, fontWeight: "bold", textTransform: "uppercase", letterSpacing: 1 },
  mrrValueRow: { flexDirection: 'row', alignItems: 'flex-end', marginBottom: 20 },
  mrrValue: { color: "#FFF", fontSize: 44, fontWeight: "900", letterSpacing: -2 },
  badgeGrowth: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, marginLeft: 12, marginBottom: 8, borderWidth: 1 },
  badgeGrowthText: { fontSize: 13, fontWeight: '900' },
  mrrHistoryRow: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.1)", paddingTop: 15, marginBottom: 15 },
  mrrHistoryItem: { flex: 1 },
  mrrHistoryLabel: { color: "#888", fontSize: 11, fontWeight: "bold", textTransform: "uppercase", marginBottom: 4 },
  mrrHistoryValue: { color: "#FFF", fontSize: 16, fontWeight: "900" },
  metaProgressoContainer: { backgroundColor: "rgba(255,255,255,0.03)", padding: 15, borderRadius: 16, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  metaProgressoHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  metaProgressoLabel: { color: "#FFF", fontSize: 12, fontWeight: "bold" },
  metaProgressoValue: { color: "#0A84FF", fontSize: 12, fontWeight: "900" },
  metaBarBg: { height: 8, backgroundColor: "#222", borderRadius: 4, overflow: 'hidden' },
  metaBarFill: { height: '100%', backgroundColor: "#0A84FF", borderRadius: 4 },
  insightPredicaoBox: { flexDirection: 'row', backgroundColor: "rgba(10, 132, 255, 0.1)", padding: 15, borderRadius: 16, marginTop: 15, borderWidth: 1, borderColor: "rgba(10, 132, 255, 0.2)", alignItems: 'center' },
  insightPredicaoText: { flex: 1, color: "#0A84FF", fontSize: 12, fontWeight: "bold", marginLeft: 10, lineHeight: 18 },

  kpiGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", marginBottom: 10 },
  kpiBox: { width: "48%", backgroundColor: "#121212", borderRadius: 20, padding: 18, borderWidth: 1, borderColor: "#222", marginBottom: 15 },
  kpiIconBg: { width: 36, height: 36, borderRadius: 12, justifyContent: "center", alignItems: "center", marginBottom: 12 },
  kpiLabel: { color: "#888", fontSize: 11, fontWeight: "bold", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 4 },
  kpiValue: { color: "#FFF", fontSize: 20, fontWeight: "900" },

  distContainer: { backgroundColor: "#121212", borderRadius: 24, padding: 20, borderWidth: 1, borderColor: "#222", marginBottom: 25 },
  stackedBar: { flexDirection: 'row', height: 16, borderRadius: 8, overflow: 'hidden', marginBottom: 20, backgroundColor: '#222' },
  distLegendContainer: { flexDirection: 'column', gap: 12 },
  distLegendItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  distLegendLeft: { flexDirection: 'row', alignItems: 'center' },
  distDot: { width: 10, height: 10, borderRadius: 5, marginRight: 8 },
  distLabel: { color: "#AAA", fontSize: 13, fontWeight: "bold" },
  distValue: { color: "#FFF", fontSize: 14, fontWeight: "900" },

  funilContainer: { backgroundColor: "#121212", borderRadius: 24, padding: 20, borderWidth: 1, borderColor: "#222", marginBottom: 25 },
  funilEtapa: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  funilBarBg: { flex: 1, height: 35, backgroundColor: "#1A1A1A", borderRadius: 12, overflow: 'hidden', marginLeft: 15, justifyContent: 'center' },
  funilBarFill: { position: 'absolute', top: 0, bottom: 0, left: 0, borderRadius: 12 },
  funilEtapaLabel: { width: 85, color: "#AAA", fontSize: 12, fontWeight: "bold" },
  funilEtapaValue: { color: "#FFF", fontSize: 14, fontWeight: "900", position: 'absolute', right: 15, zIndex: 2 },
  
  funilTempoRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15, paddingTop: 15, borderTopWidth: 1, borderTopColor: "#222" },
  funilTempoBox: { flex: 1, backgroundColor: "rgba(255,255,255,0.03)", padding: 12, borderRadius: 12, alignItems: 'center', marginHorizontal: 4, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  funilTempoLabel: { color: "#888", fontSize: 10, fontWeight: "bold", textTransform: "uppercase", marginBottom: 4, textAlign: 'center' },
  funilTempoValue: { color: "#FFF", fontSize: 16, fontWeight: "900" },

  selosGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 20 },
  seloCard: { width: '30%', backgroundColor: "rgba(255,215,0,0.05)", borderRadius: 16, padding: 15, alignItems: 'center', borderWidth: 1, borderColor: "rgba(255,215,0,0.3)" },
  seloIconBox: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(255,215,0,0.15)", justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  seloTitle: { color: "#FFD700", fontSize: 11, fontWeight: "bold", textAlign: 'center' },

  modalContainer: { flex: 1, justifyContent: "flex-end" },
  modalCard: { backgroundColor: "#121212", borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 24, paddingBottom: Platform.OS === "ios" ? 40 : 24, borderWidth: 1, borderColor: "#222" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 },
  modalTitle: { color: "#FFF", fontSize: 20, fontWeight: "900", letterSpacing: -0.5 },
  modalCloseBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#1A1A1A", justifyContent: "center", alignItems: "center" },
  inputLabel: { color: "#888", fontSize: 12, fontWeight: "bold", textTransform: "uppercase", marginBottom: 8 },
  inputBox: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1A", borderRadius: 16, paddingHorizontal: 16, height: 60, marginBottom: 20, borderWidth: 1, borderColor: "#333" },
  inputPrefix: { color: "#666", fontSize: 16, fontWeight: "bold", marginRight: 8 },
  input: { flex: 1, color: "#FFF", fontSize: 16, fontWeight: "600", height: "100%", outlineStyle: "none" },
  btnConfirmar: { flexDirection: "row", backgroundColor: "#0A84FF", height: 60, borderRadius: 16, justifyContent: "center", alignItems: "center", marginTop: 10 },
  btnConfirmarText: { color: "#FFF", fontSize: 16, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.5 },

  aiCardContainer: { backgroundColor: "rgba(160, 32, 240, 0.1)", borderRadius: 24, padding: 20, borderWidth: 1, borderColor: "rgba(160, 32, 240, 0.4)", marginBottom: 25, shadowColor: "#A020F0", shadowOffset: {width: 0, height: 4}, shadowOpacity: 0.2, shadowRadius: 10 },
  aiHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  aiTitle: { color: "#FFF", fontSize: 16, fontWeight: "900", marginLeft: 8, letterSpacing: 0.5 },
  aiText: { color: "#E0E0E0", fontSize: 13, lineHeight: 20 },
});