import { StyleSheet, Platform } from "react-native";
import { theme } from "../../../../theme/theme";
import { scale, verticalScale, moderateScale } from "../../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  center: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: theme.colors.background },

  headerBackground: { paddingHorizontal: scale(24), paddingTop: Platform.OS === "ios" ? verticalScale(70) : verticalScale(50), paddingBottom: verticalScale(70), borderBottomLeftRadius: moderateScale(36), borderBottomRightRadius: moderateScale(36) },
  headerTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  greeting: { color: theme.colors.primary, fontSize: moderateScale(12), fontWeight: "800", letterSpacing: 1.5, marginBottom: verticalScale(4) },
  personalName: { color: theme.colors.text, fontSize: moderateScale(28), fontFamily: theme.fonts.title, letterSpacing: 0.5 },
  headerActionsRight: { flexDirection: "row", alignItems: "center" },
  btnLogout: { width: scale(44), height: scale(44), borderRadius: moderateScale(22), backgroundColor: "rgba(255, 59, 48, 0.15)", justifyContent: "center", alignItems: "center", marginRight: scale(16) },
  settingsBtn: { position: "relative" },
  headerAvatar: { width: scale(64), height: scale(64), borderRadius: moderateScale(32), borderWidth: 2, borderColor: theme.colors.border },
  settingsOverlay: { position: "absolute", bottom: 0, right: 0, backgroundColor: theme.colors.primary, width: scale(24), height: scale(24), borderRadius: moderateScale(12), justifyContent: "center", alignItems: "center", borderWidth: 2, borderColor: theme.colors.surface },

  statsWrapper: { paddingHorizontal: scale(20), marginTop: verticalScale(-45), zIndex: 10 },
  statsContainer: { flexDirection: "row", justifyContent: "space-between", backgroundColor: theme.colors.surface, borderRadius: moderateScale(24), paddingVertical: verticalScale(20), paddingHorizontal: scale(15), borderWidth: 1, borderColor: theme.colors.borderLight, shadowColor: "#000", shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 5 },
  statItem: { flex: 1, alignItems: "center" },
  iconWrapperNeutral: { backgroundColor: theme.colors.surfaceLight, padding: scale(8), borderRadius: moderateScale(12), marginBottom: verticalScale(8) },
  iconWrapperPrimary: { backgroundColor: "rgba(255, 107, 0, 0.15)", padding: scale(8), borderRadius: moderateScale(12), marginBottom: verticalScale(8) },
  iconWrapperAlert: { backgroundColor: "rgba(255, 107, 0, 0.15)", padding: scale(8), borderRadius: moderateScale(12), marginBottom: verticalScale(8) },
  statValue: { color: theme.colors.text, fontSize: moderateScale(20), fontWeight: "900" },
  statLabel: { color: theme.colors.textSecondary, fontSize: moderateScale(11), fontWeight: "bold", textTransform: "uppercase", marginTop: verticalScale(2), letterSpacing: 0.5 },
  statDivider: { width: 1, backgroundColor: "rgba(255, 107, 0, 0.2)", marginHorizontal: scale(2), marginVertical: verticalScale(10) },

  scrollContent: { padding: scale(20), paddingBottom: verticalScale(80) },

  quickAccessGrid: { flexDirection: "row", justifyContent: "space-between", gap: scale(12), marginTop: verticalScale(10), marginBottom: verticalScale(12) },
  quickAccessCard: { flex: 1, backgroundColor: theme.colors.surface, borderRadius: moderateScale(20), padding: scale(16), borderWidth: 1, borderColor: theme.colors.borderLight, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 3 },
  quickAccessHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: verticalScale(12) },
  quickAccessIcon: { width: scale(40), height: scale(40), borderRadius: moderateScale(12), justifyContent: "center", alignItems: "center" },
  quickAccessTitle: { color: theme.colors.text, fontSize: moderateScale(15), fontWeight: "bold", marginBottom: verticalScale(2), letterSpacing: 0.2 },
  quickAccessSubtitle: { color: theme.colors.textSecondary, fontSize: moderateScale(12) },

  fullWidthCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.colors.surface, borderRadius: moderateScale(20), padding: scale(16), marginBottom: verticalScale(15), borderWidth: 1, borderColor: theme.colors.borderLight, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 3 },
  fullWidthCardIconBg: { width: scale(48), height: scale(48), borderRadius: moderateScale(14), backgroundColor: "rgba(255, 107, 0, 0.15)", justifyContent: 'center', alignItems: 'center', marginRight: scale(12) },
  fullWidthCardText: { flex: 1 },
  fullWidthCardTitle: { color: theme.colors.text, fontSize: moderateScale(16), fontWeight: 'bold', marginBottom: verticalScale(2) },
  fullWidthCardSubtitle: { color: theme.colors.textSecondary, fontSize: moderateScale(13) },

  crmHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: verticalScale(20), marginTop: verticalScale(25) },
  sectionTitle: { color: theme.colors.text, fontSize: moderateScale(22), fontFamily: theme.fonts.title },
  headerActions: { flexDirection: "row", gap: scale(10) },
  actionHeaderBtn: { width: scale(40), height: scale(40), borderRadius: moderateScale(12), backgroundColor: theme.colors.primary, justifyContent: "center", alignItems: "center" },

  segmentControl: { flexDirection: "row", backgroundColor: theme.colors.surface, borderRadius: moderateScale(20), padding: scale(6), marginBottom: verticalScale(16), borderWidth: 1, borderColor: "#222" },
  segmentBtn: { flex: 1, paddingVertical: verticalScale(14), borderRadius: moderateScale(16), alignItems: "center", borderWidth: 1, borderColor: "transparent" },
  segmentBtnActive: { backgroundColor: "rgba(255, 107, 0, 0.1)", borderColor: theme.colors.primary, shadowColor: theme.colors.primary, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 8, elevation: 5 },
  segmentText: { color: theme.colors.textSecondary, fontSize: moderateScale(13), fontWeight: "700" },
  segmentTextActive: { color: theme.colors.primary, fontWeight: "900" },

  searchSortContainer: { flexDirection: "row", alignItems: "center", marginBottom: verticalScale(20), gap: scale(10) },
  searchBar: { flex: 1, flexDirection: "row", alignItems: "center", backgroundColor: theme.colors.surfaceLight, height: verticalScale(50), borderRadius: moderateScale(16), paddingHorizontal: scale(16), borderWidth: 1, borderColor: theme.colors.border },
  searchInput: { flex: 1, color: theme.colors.text, fontSize: moderateScale(15), marginLeft: scale(10), fontFamily: theme.fonts.body, height: "100%" },
  sortBtn: { width: scale(50), height: scale(50), borderRadius: moderateScale(16), backgroundColor: "rgba(255, 107, 0, 0.1)", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "rgba(255, 107, 0, 0.3)" },

  secondaryFilterContainer: { flexDirection: "row", gap: scale(10), marginBottom: verticalScale(20), paddingHorizontal: scale(2) },
  secondaryFilterChip: { paddingHorizontal: scale(16), paddingVertical: verticalScale(8), borderRadius: moderateScale(20), backgroundColor: theme.colors.surfaceLight, borderWidth: 1, borderColor: theme.colors.borderLight },
  secondaryFilterChipActive: { backgroundColor: "rgba(255, 107, 0, 0.15)", borderColor: theme.colors.primary },
  secondaryFilterText: { color: theme.colors.textSecondary, fontSize: moderateScale(12), fontWeight: "700" },
  secondaryFilterTextActive: { color: theme.colors.primary, fontWeight: "900" },

  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", justifyContent: "flex-end" },
  bottomSheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: moderateScale(30), borderTopRightRadius: moderateScale(30), paddingHorizontal: scale(24), paddingVertical: verticalScale(24), paddingBottom: Platform.OS === "ios" ? verticalScale(40) : verticalScale(24), borderWidth: 1, borderColor: theme.colors.border },
  sheetHandle: { width: scale(40), height: verticalScale(5), borderRadius: moderateScale(3), backgroundColor: "#444", alignSelf: "center", marginBottom: verticalScale(20) },
  sheetTitle: { color: "#FFF", fontSize: moderateScale(20), fontFamily: theme.fonts.title, marginBottom: verticalScale(10), textAlign: "center" },
  sheetSectionTitle: { color: theme.colors.textSecondary, fontSize: moderateScale(12), fontWeight: "bold", textTransform: "uppercase", marginTop: verticalScale(15), marginBottom: verticalScale(10), letterSpacing: 0.5 },
  sheetFilterRow: { flexDirection: "row", gap: scale(10), marginBottom: verticalScale(10) },
  sheetFilterChip: { flex: 1, paddingVertical: verticalScale(12), backgroundColor: theme.colors.surfaceLight, borderRadius: moderateScale(14), alignItems: "center", borderWidth: 1, borderColor: theme.colors.borderLight },
  sheetFilterChipActive: { backgroundColor: "rgba(255, 107, 0, 0.15)", borderColor: theme.colors.primary },
  sheetFilterChipText: { color: theme.colors.textSecondary, fontSize: moderateScale(13), fontWeight: "600" },
  sheetFilterChipTextActive: { color: theme.colors.primary, fontWeight: "bold" },
  sortOption: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: verticalScale(16), borderBottomWidth: 1, borderBottomColor: theme.colors.borderLight },
  sortOptionText: { color: theme.colors.textSecondary, fontSize: moderateScale(16), fontWeight: "600" },
  sortOptionTextActive: { color: theme.colors.primary, fontWeight: "bold" },
  sheetBtnClose: { marginTop: verticalScale(25), backgroundColor: theme.colors.primary, paddingVertical: verticalScale(16), borderRadius: moderateScale(16), alignItems: "center", shadowColor: theme.colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 5 },
  sheetBtnCloseText: { color: "#000", fontSize: moderateScale(15), fontWeight: "900", textTransform: "uppercase" },

  studentCardPremium: { backgroundColor: "#111", borderRadius: moderateScale(16), marginBottom: verticalScale(16), borderWidth: 1, borderColor: "#222", borderLeftWidth: 4, shadowColor: "#000", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.2, shadowRadius: 10, elevation: 4, overflow: 'hidden' },
  cardHeaderArea: { flexDirection: "row", alignItems: "center", padding: scale(16) },
  avatarWrapper: { position: "relative", marginRight: scale(14) },
  avatarImage: { width: scale(50), height: scale(50), borderRadius: moderateScale(25), backgroundColor: "#222" },
  avatarPlaceholder: { width: scale(50), height: scale(50), borderRadius: moderateScale(25), backgroundColor: "#1A1A1A", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "#333" },
  statusIndicatorOnline: { position: "absolute", bottom: -2, right: -2, width: scale(14), height: scale(14), borderRadius: scale(7), backgroundColor: "#00E676", borderWidth: 2, borderColor: "#111" },
  statusIndicatorMessage: { position: "absolute", top: -2, right: -2, width: scale(16), height: scale(16), borderRadius: scale(8), backgroundColor: theme.colors.primary, borderWidth: 2, borderColor: "#111" },
  headerInfoWrapper: { flex: 1, justifyContent: "center" },
  nameAndDateRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: verticalScale(6) },
  studentNameText: { color: "#FFF", fontSize: moderateScale(16), fontWeight: "700", letterSpacing: 0.2, flexShrink: 1 },
  studentAgeText: { color: "#888", fontWeight: "500" },
  dateText: { color: "#666", fontSize: moderateScale(11), fontWeight: "600", marginLeft: scale(8) },
  tagsRow: { flexDirection: "row", alignItems: "center", gap: scale(6), marginBottom: verticalScale(6) },
  orangePill: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255, 107, 0, 0.1)", borderWidth: 1, borderColor: "rgba(255, 107, 0, 0.25)", paddingHorizontal: scale(8), paddingVertical: verticalScale(4), borderRadius: moderateScale(6) },
  orangePillText: { color: theme.colors.primary, fontSize: moderateScale(10), fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.5 },
  metricsRow: { flexDirection: "row", alignItems: "center" },
  metricBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1A1A1A', paddingHorizontal: scale(6), paddingVertical: verticalScale(2), borderRadius: moderateScale(4), borderWidth: 1, borderColor: '#2A2A2A', marginRight: scale(6) },
  metricBadgeText: { color: '#888', fontSize: moderateScale(10), fontWeight: '600', marginLeft: scale(4) },
  cardDivider: { height: 1, backgroundColor: "#222", marginHorizontal: scale(16) },
  cardFooterArea: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: scale(16), paddingVertical: verticalScale(12) },
  originIndicator: { flexDirection: "row", alignItems: "center", gap: scale(4) },
  originIndicatorText: { fontSize: moderateScale(10), fontWeight: "800", letterSpacing: 0.5 },
  alertWrapper: { flexDirection: "row", alignItems: "center" },
  badgeAlertGold: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255, 215, 0, 0.1)", borderWidth: 1, borderColor: "rgba(255, 215, 0, 0.2)", paddingHorizontal: scale(8), paddingVertical: verticalScale(4), borderRadius: moderateScale(6), gap: scale(4) },
  badgeAlertGoldText: { color: "#FFD700", fontSize: moderateScale(9), fontWeight: "800", textTransform: "uppercase" },
  badgeAlertDanger: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255, 59, 48, 0.1)", borderWidth: 1, borderColor: "rgba(255, 59, 48, 0.2)", paddingHorizontal: scale(8), paddingVertical: verticalScale(4), borderRadius: moderateScale(6), gap: scale(4) },
  badgeAlertDangerText: { color: "#FF3B30", fontSize: moderateScale(9), fontWeight: "800", textTransform: "uppercase" },
  badgeAlertNeutral: { flexDirection: "row", alignItems: "center", backgroundColor: "#1A1A1A", borderWidth: 1, borderColor: "#333", paddingHorizontal: scale(8), paddingVertical: verticalScale(4), borderRadius: moderateScale(6), gap: scale(4) },
  badgeAlertNeutralText: { color: "#AAA", fontSize: moderateScale(9), fontWeight: "800", textTransform: "uppercase" },
  emptyState: { alignItems: "center", marginTop: verticalScale(40), padding: scale(20) },
  emptyIconBg: { width: scale(88), height: scale(88), borderRadius: moderateScale(44), backgroundColor: theme.colors.surface, justifyContent: "center", alignItems: "center", marginBottom: verticalScale(20), borderWidth: 1, borderColor: theme.colors.borderLight },
  emptyTitle: { color: theme.colors.text, fontSize: moderateScale(20), fontWeight: "bold", marginBottom: verticalScale(10) },
  emptyText: { color: theme.colors.textSecondary, fontSize: moderateScale(14), textAlign: "center", lineHeight: moderateScale(22), paddingHorizontal: scale(20) },
});