import { Platform, StyleSheet, StatusBar } from "react-native";
import { moderateScale, scale, verticalScale } from "../../../utils/responsive";

const STATUSBAR_HEIGHT = Platform.OS === 'android' ? StatusBar.currentHeight : 0;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#050505" },
  center: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#050505" },
  scrollContent: { paddingBottom: verticalScale(80) },
  absoluteFill: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0 },

  studentHeader: { 
    flexDirection: "row", 
    justifyContent: "space-between", 
    alignItems: "center", 
    paddingHorizontal: scale(20), 
    paddingTop: Platform.OS === "ios" ? verticalScale(50) : (STATUSBAR_HEIGHT || 0) + verticalScale(15),
    paddingBottom: verticalScale(15), 
    borderBottomWidth: 1, 
    borderBottomColor: "#111", 
    backgroundColor: "#0A0A0A" 
  },
  studentHeaderLeft: { flexDirection: "row", alignItems: "center", flex: 1 },
  studentAvatar: { width: scale(44), height: scale(44), borderRadius: moderateScale(22), borderWidth: 1, borderColor: "#333" },
  studentGreeting: { color: "#FFF", fontSize: moderateScale(16), fontWeight: "bold" },
  studentSub: { color: "#888", fontSize: moderateScale(12) },
  studentHeaderRight: { flexDirection: "row", alignItems: "center" },
  btnIcon: { width: scale(40), height: scale(40), borderRadius: moderateScale(20), backgroundColor: "#151515", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "#222" },

  dashboardSection: { paddingHorizontal: scale(20), marginTop: verticalScale(20) },
  sectionTitle: { color: "#FFF", fontSize: moderateScale(16), fontWeight: "900", marginBottom: verticalScale(12) },

  trainerPremiumCard: { backgroundColor: "#0A0A0A", borderRadius: moderateScale(20), borderWidth: 1, borderColor: "#1A1A1A", overflow: "hidden", marginBottom: verticalScale(10) },
  trainerRow: { flexDirection: "row", alignItems: "center", padding: scale(20) },
  trainerAvatarLarge: { width: scale(64), height: scale(64), borderRadius: moderateScale(32), backgroundColor: "#151515", justifyContent: "center", alignItems: "center", borderWidth: 2, borderColor: "#FF6B00", overflow: "hidden" },
  trainerInfo: { flex: 1, marginLeft: scale(15) },
  trainerName: { color: "#FFF", fontSize: moderateScale(18), fontWeight: "bold", marginBottom: verticalScale(2) },
  trainerSpec: { color: "#AAA", fontSize: moderateScale(12), marginBottom: verticalScale(8) },
  crefBadge: { flexDirection: "row", alignItems: "center", backgroundColor: "#111", paddingHorizontal: scale(8), paddingVertical: verticalScale(4), borderRadius: moderateScale(8), alignSelf: "flex-start", borderWidth: 1, borderColor: "#222" },
  crefText: { color: "#888", fontSize: moderateScale(10), fontWeight: "bold", marginLeft: scale(4) },
  trainerActionsRow: { flexDirection: "row", borderTopWidth: 1, borderTopColor: "#151515" },
  btnTrainerAction: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: verticalScale(14), borderRightWidth: 1, borderRightColor: "#151515" },
  btnTrainerActionText: { color: "#FFF", fontSize: moderateScale(13), fontWeight: "bold" },

  calendarRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: verticalScale(8), backgroundColor: "#0A0A0A", padding: scale(16), borderRadius: moderateScale(20), borderWidth: 1, borderColor: "#1A1A1A" },
  dayBox: { alignItems: "center", width: scale(38), paddingVertical: verticalScale(10), borderRadius: moderateScale(12), backgroundColor: "#111", borderWidth: 1, borderColor: "#222" },
  dayBoxHoje: { backgroundColor: "rgba(255, 107, 0, 0.1)", borderColor: "rgba(255, 107, 0, 0.4)" },
  dayLabel: { color: "#888", fontSize: moderateScale(10), fontWeight: "bold", marginBottom: verticalScale(6) },
  dayDate: { color: "#CCC", fontSize: moderateScale(15), fontWeight: "900" },
  statusDot: { width: scale(6), height: scale(6), borderRadius: moderateScale(3), marginTop: verticalScale(6) },
  statusDotConcluido: { width: scale(14), height: scale(14), borderRadius: moderateScale(7), backgroundColor: "#00E676", justifyContent: "center", alignItems: "center", marginTop: verticalScale(3), shadowColor: "#00E676", shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.8, shadowRadius: 4, elevation: 3 },
  emptyHintText: { color: "#555", fontSize: moderateScale(12), textAlign: "center", fontStyle: "italic", marginBottom: verticalScale(15) },

  checkinCardPendente: { flexDirection: "row", backgroundColor: "rgba(255, 107, 0, 0.1)", borderRadius: moderateScale(20), padding: scale(16), borderWidth: 1, borderColor: "rgba(255, 107, 0, 0.4)", marginBottom: verticalScale(15), alignItems: "center" },
  checkinIconBox: { width: scale(48), height: scale(48), borderRadius: moderateScale(24), backgroundColor: "rgba(255, 107, 0, 0.2)", justifyContent: "center", alignItems: "center", position: "relative" },
  checkinAlertDot: { position: "absolute", top: 0, right: 0, width: scale(12), height: scale(12), borderRadius: moderateScale(6), backgroundColor: "#FF3B30", borderWidth: 2, borderColor: "#000" },
  checkinContent: { flex: 1, marginLeft: scale(15) },
  checkinTitle: { color: "#FFF", fontSize: moderateScale(15), fontWeight: "bold", marginBottom: verticalScale(4) },
  checkinDesc: { color: "#AAA", fontSize: moderateScale(12), lineHeight: moderateScale(16), marginBottom: verticalScale(8) },
  checkinBtn: { flexDirection: "row", alignItems: "center", backgroundColor: "#FF6B00", paddingHorizontal: scale(12), paddingVertical: verticalScale(6), borderRadius: moderateScale(10), alignSelf: "flex-start" },
  checkinBtnText: { color: "#000", fontSize: moderateScale(12), fontWeight: "900" },
  
  checkinCardNeutro: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255, 107, 0, 0.03)", borderRadius: moderateScale(16), padding: scale(16), borderWidth: 1, borderColor: "rgba(255, 107, 0, 0.3)", marginBottom: verticalScale(15) },

  btnVerTodos: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255, 107, 0, 0.1)', paddingHorizontal: scale(12), paddingVertical: verticalScale(6), borderRadius: moderateScale(12) },
  btnVerTodosText: { color: "#FF6B00", fontSize: moderateScale(12), fontWeight: "bold", marginRight: scale(4) },
  workoutCard: { borderRadius: moderateScale(20), marginBottom: verticalScale(12), overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,107,0,0.3)" },
  workoutCardBg: { ...StyleSheet.absoluteFill },
  workoutCardContent: { padding: scale(20) },
  workoutHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: verticalScale(12) },
  workoutTitle: { color: "#FFF", fontSize: moderateScale(20), fontWeight: "900" },
  workoutSpecs: { flexDirection: "row", gap: scale(12), marginBottom: verticalScale(20) },
  workoutSpecItem: { flexDirection: "row", alignItems: "center", gap: scale(4) },
  workoutSpecText: { color: "#CCC", fontSize: moderateScale(12), fontWeight: "bold" },
  btnStartWorkout: { backgroundColor: "#FFF", paddingVertical: verticalScale(14), borderRadius: moderateScale(12), alignItems: "center" },
  btnStartWorkoutText: { color: "#000", fontSize: moderateScale(14), fontWeight: "900", textTransform: "uppercase" },
  
  emptyWorkoutCard: { backgroundColor: "rgba(255, 107, 0, 0.03)", borderRadius: moderateScale(20), padding: scale(30), alignItems: "center", borderWidth: 1, borderColor: "rgba(255, 107, 0, 0.3)", marginBottom: verticalScale(15) },
  emptyWorkoutTitle: { color: "#FFF", fontSize: moderateScale(16), fontWeight: "bold", marginBottom: verticalScale(4) },
  emptyWorkoutDesc: { color: "#888", fontSize: moderateScale(12), textAlign: "center" },

  feedbackBubble: { backgroundColor: "rgba(255, 107, 0, 0.05)", borderRadius: moderateScale(16), padding: scale(16), borderWidth: 1, borderColor: "rgba(255, 107, 0, 0.3)", marginBottom: verticalScale(10), flexDirection: "row" },
  feedbackText: { color: "#CCC", fontSize: moderateScale(13), lineHeight: moderateScale(18), flex: 1, marginLeft: scale(12) },
  feedbackBubbleEmpty: { backgroundColor: "rgba(255, 107, 0, 0.03)", borderRadius: moderateScale(16), padding: scale(16), borderWidth: 1, borderColor: "rgba(255, 107, 0, 0.3)", marginBottom: verticalScale(10), flexDirection: "row", alignItems: "center" },
  feedbackTextEmpty: { color: "#888", fontSize: moderateScale(12), flex: 1, marginLeft: scale(12), fontStyle: "italic" },

  financeiroCard: { flexDirection: 'row', alignItems: 'center', padding: scale(16), borderRadius: moderateScale(16), borderWidth: 1, marginBottom: verticalScale(25) },
  financeiroIconBox: { width: scale(44), height: scale(44), borderRadius: moderateScale(12), justifyContent: 'center', alignItems: 'center' },
  financeiroTitle: { color: "#FFF", fontSize: moderateScale(14), fontWeight: "bold" },
  financeiroSub: { fontSize: moderateScale(12), fontWeight: "bold", marginTop: verticalScale(4) },
  gridActionsPremium: { flexDirection: 'row', justifyContent: 'space-between', gap: scale(12), marginBottom: verticalScale(25) },
  actionCardPremium: { flex: 1, backgroundColor: "#0A0A0A", borderRadius: moderateScale(16), padding: scale(16), borderWidth: 1, borderColor: "#151515", overflow: "hidden", position: "relative" },
  actionIconWrapper: { width: scale(44), height: scale(44), borderRadius: moderateScale(12), justifyContent: 'center', alignItems: 'center' },
  actionCardTitle: { color: "#FFF", fontSize: moderateScale(15), fontWeight: "bold", marginBottom: verticalScale(4) },
  actionCardDesc: { color: "#888", fontSize: moderateScale(11), fontWeight: "600" },
  trackerCard: { backgroundColor: "#0A0A0A", borderRadius: moderateScale(20), padding: scale(20), borderWidth: 1, borderColor: "#151515", marginBottom: verticalScale(20) },
  trackerHeader: { flexDirection: "row", alignItems: "center", gap: scale(8), marginBottom: verticalScale(8) },
  trackerTitle: { color: "#FFF", fontSize: moderateScale(14), fontWeight: "bold" },
  trackerDesc: { color: "#888", fontSize: moderateScale(12), marginBottom: verticalScale(16) },
  progressBarContainer: { height: verticalScale(8), backgroundColor: "#222", borderRadius: moderateScale(4), overflow: "hidden" },
  progressBarFill: { height: "100%", backgroundColor: "#FF6B00", borderRadius: moderateScale(4) },
  progressLabels: { flexDirection: "row", justifyContent: "space-between", marginTop: verticalScale(8) },
  progressLabelLeft: { color: "#FF6B00", fontSize: moderateScale(11), fontWeight: "bold" },
  progressLabelRight: { color: "#666", fontSize: moderateScale(11), fontWeight: "bold" },
  footerRow: { paddingHorizontal: scale(20), marginBottom: verticalScale(20) },
  btnDangerOutline: { paddingVertical: verticalScale(14), borderRadius: moderateScale(16), borderWidth: 1, borderColor: "rgba(255,59,48,0.3)", alignItems: "center" },
  btnDangerText: { color: "#FF3B30", fontSize: moderateScale(13), fontWeight: "bold" },
});